export const buildRoute = (...segments: string[]) => segments.filter(Boolean).join('/');
export const toCommands = (path: string): string[] => ['/', ...path.split('/').filter(Boolean)];

export const AppRoutes = {
  Login: 'login',
  Register: 'register',
  ForgotPassword: 'forgot-password',
  ResetPassword: 'reset-password',
  AdminRoot: 'admin',
  ClientRoot: 'client',
  Dashboard: 'dashboard',
  Finance: 'finance',
  Account: 'account',
  Profile: 'profile',
  Security: 'security',
  Users: 'users',
  Add: 'add',
  Edit: 'edit',
  Detail: 'detail',
  Compare: 'compare',
  Menu: 'menu',
  Notifications: 'notifications',
  Watchlist: 'watchlist',
  Portfolio: 'portfolio',
  Analysis: 'analysis',
  History: 'history',
  Simulation: 'simulation',
  Patterns: 'patterns',
  Instruments: 'instruments',
  InstrumentRegistry: 'instrument-registry',
  PeaRegistry: 'pea-registry',
  ScoringPolicy: 'scoring-policy',
  ParameterDictionary: 'parameter-dictionary',
  WordingVersions: 'wording-versions',
  SnapshotAudit: 'snapshot-audit',
  DataQuality: 'data-quality',
  Parameters: 'parameters',
  Learn: 'learn',
  Help: 'help',
  Contact: 'contact',
  Onboarding: 'onboarding',
  Kpi: 'kpi',
  SignalQuality: 'signal-quality',
  Engagement: 'engagement',
  Privacy: 'privacy',
  Alerts: 'alerts',
  DataExport: 'data-export',
  DeleteAccount: 'delete',
  Legal: 'legal',
  Education: 'education',
  Glossary: 'glossary',
  Faq: 'faq',
  LegalCards: 'legal-cards',
  LearnTopics: 'learn-topics',
  AnalysisContent: 'analysis-content',
  Tax: 'tax',
  Screener: 'screener'
} as const;

export const AuthPaths = {
  Login: AppRoutes.Login,
  Register: AppRoutes.Register,
  ForgotPassword: AppRoutes.ForgotPassword,
  ResetPassword: AppRoutes.ResetPassword
} as const;

export const AdminPaths = {
  Dashboard: buildRoute(AppRoutes.AdminRoot, AppRoutes.Dashboard),
  UsersList: buildRoute(AppRoutes.AdminRoot, AppRoutes.Users),
  UserAdd: buildRoute(AppRoutes.AdminRoot, AppRoutes.Users, AppRoutes.Add),
  UserEdit: (id: string) => buildRoute(AppRoutes.AdminRoot, AppRoutes.Users, AppRoutes.Edit, id),
  InstrumentRegistry: buildRoute(AppRoutes.AdminRoot, AppRoutes.InstrumentRegistry),
  PeaRegistry: buildRoute(AppRoutes.AdminRoot, AppRoutes.PeaRegistry),
  ScoringPolicy: buildRoute(AppRoutes.AdminRoot, AppRoutes.ScoringPolicy),
  ParameterDictionary: buildRoute(AppRoutes.AdminRoot, AppRoutes.ParameterDictionary),
  ParameterDictionaryDetail: (parameterId: string) => buildRoute(AppRoutes.AdminRoot, AppRoutes.ParameterDictionary, AppRoutes.Detail, parameterId),
  WordingVersions: buildRoute(AppRoutes.AdminRoot, AppRoutes.WordingVersions),
  WordingVersionsDetail: (wordingVersionId: string) => buildRoute(AppRoutes.AdminRoot, AppRoutes.WordingVersions, AppRoutes.Detail, wordingVersionId),
  SnapshotAudit: buildRoute(AppRoutes.AdminRoot, AppRoutes.SnapshotAudit),
  SnapshotAuditDetail: (analysisRunId: string) => buildRoute(AppRoutes.AdminRoot, AppRoutes.SnapshotAudit, AppRoutes.Detail, analysisRunId),
  SnapshotAuditCompare: buildRoute(AppRoutes.AdminRoot, AppRoutes.SnapshotAudit, AppRoutes.Compare),
  DataQuality: buildRoute(AppRoutes.AdminRoot, AppRoutes.DataQuality),
  KpiSignalQuality: buildRoute(AppRoutes.AdminRoot, AppRoutes.Kpi, AppRoutes.SignalQuality),
  KpiEngagement: buildRoute(AppRoutes.AdminRoot, AppRoutes.Kpi, AppRoutes.Engagement),
  Education: buildRoute(AppRoutes.AdminRoot, AppRoutes.Education),
  EducationAdd: buildRoute(AppRoutes.AdminRoot, AppRoutes.Education, AppRoutes.Add),
  EducationEdit: (id: number) => buildRoute(AppRoutes.AdminRoot, AppRoutes.Education, AppRoutes.Edit, String(id)),
  EducationDetail: (slug: string) => buildRoute(AppRoutes.AdminRoot, AppRoutes.Education, slug),
  Glossary: buildRoute(AppRoutes.AdminRoot, AppRoutes.Glossary),
  GlossaryAdd: buildRoute(AppRoutes.AdminRoot, AppRoutes.Glossary, AppRoutes.Add),
  GlossaryEdit: (id: number) => buildRoute(AppRoutes.AdminRoot, AppRoutes.Glossary, AppRoutes.Edit, String(id)),
  Faq: buildRoute(AppRoutes.AdminRoot, 'faq'),
  FaqAdd: buildRoute(AppRoutes.AdminRoot, 'faq', AppRoutes.Add),
  FaqEdit: (id: number) => buildRoute(AppRoutes.AdminRoot, 'faq', AppRoutes.Edit, String(id)),
  LegalCards: buildRoute(AppRoutes.AdminRoot, 'legal-cards'),
  LegalCardsAdd: buildRoute(AppRoutes.AdminRoot, 'legal-cards', AppRoutes.Add),
  LegalCardsEdit: (id: number) => buildRoute(AppRoutes.AdminRoot, 'legal-cards', AppRoutes.Edit, String(id)),
  LearnTopics: buildRoute(AppRoutes.AdminRoot, 'learn-topics'),
  LearnTopicsAdd: buildRoute(AppRoutes.AdminRoot, 'learn-topics', AppRoutes.Add),
  LearnTopicsEdit: (id: number) => buildRoute(AppRoutes.AdminRoot, 'learn-topics', AppRoutes.Edit, String(id)),
  AnalysisContent: buildRoute(AppRoutes.AdminRoot, AppRoutes.AnalysisContent)
} as const;

export const UserPaths = {
  Dashboard: buildRoute(AppRoutes.ClientRoot, AppRoutes.Dashboard),
  Finance: buildRoute(AppRoutes.ClientRoot, AppRoutes.Finance),
  Notifications: buildRoute(AppRoutes.ClientRoot, AppRoutes.Notifications),
  Watchlist: buildRoute(AppRoutes.ClientRoot, AppRoutes.Watchlist),
  Portfolio: buildRoute(AppRoutes.ClientRoot, AppRoutes.Portfolio),
  PortfolioDetail: (id: string) => buildRoute(AppRoutes.ClientRoot, AppRoutes.Portfolio, id),
  AnalysisEntry: buildRoute(AppRoutes.ClientRoot, AppRoutes.Analysis),
  AnalysisDetail: (analysisId: string) => buildRoute(AppRoutes.ClientRoot, AppRoutes.Analysis, analysisId),
  History: buildRoute(AppRoutes.ClientRoot, AppRoutes.History),
  Simulation: buildRoute(AppRoutes.ClientRoot, AppRoutes.Simulation),
  Patterns: buildRoute(AppRoutes.ClientRoot, AppRoutes.Patterns),
  InstrumentDetail: (symbol: string) => buildRoute(AppRoutes.ClientRoot, AppRoutes.Instruments, symbol),
  Account: buildRoute(AppRoutes.ClientRoot, AppRoutes.Account),
  Profile: buildRoute(AppRoutes.ClientRoot, AppRoutes.Account, AppRoutes.Profile),
  Security: buildRoute(AppRoutes.ClientRoot, AppRoutes.Account, AppRoutes.Security),
  ParameterDetail: (parameterId: string) => buildRoute(AppRoutes.ClientRoot, AppRoutes.Parameters, parameterId),
  SnapshotCompare: buildRoute(AppRoutes.ClientRoot, AppRoutes.History, AppRoutes.Compare),
  Learn: buildRoute(AppRoutes.ClientRoot, AppRoutes.Learn),
  HelpCenter: buildRoute(AppRoutes.ClientRoot, AppRoutes.Help),
  Contact: buildRoute(AppRoutes.ClientRoot, AppRoutes.Contact),
  Onboarding: buildRoute(AppRoutes.ClientRoot, AppRoutes.Onboarding),
  PrivacyConsent: buildRoute(AppRoutes.ClientRoot, AppRoutes.Account, AppRoutes.Privacy),
  AlertPreferences: buildRoute(AppRoutes.ClientRoot, AppRoutes.Account, AppRoutes.Alerts),
  DataExport: buildRoute(AppRoutes.ClientRoot, AppRoutes.Account, AppRoutes.DataExport),
  DeleteAccount: buildRoute(AppRoutes.ClientRoot, AppRoutes.Account, AppRoutes.DeleteAccount),
  LegalCenter: buildRoute(AppRoutes.ClientRoot, AppRoutes.Legal),
  Education: buildRoute(AppRoutes.ClientRoot, AppRoutes.Education),
  EducationDetail: (slug: string) => buildRoute(AppRoutes.ClientRoot, AppRoutes.Education, slug),
  Glossary: buildRoute(AppRoutes.ClientRoot, AppRoutes.Glossary),
  Tax: buildRoute(AppRoutes.ClientRoot, AppRoutes.Tax),
  Screener: buildRoute(AppRoutes.ClientRoot, AppRoutes.Screener)
} as const;

export const AppAreas = {
  Admin: AppRoutes.AdminRoot,
  User: AppRoutes.ClientRoot,
} as const;
