// <auto-generated />
using System;
using BackPredictFinance.Datas.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackPredictFinance.Datas.Migrations
{
    [DbContext(typeof(FinanceDbContext))]
    [Migration("20260609143055_AddSignalOutcome")]
    partial class AddSignalOutcome
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackPredictFinance.Datas.Entities.AnalysisRun", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasMaxLength(32000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("UserId", "StartedAtUtc");

                    b.ToTable("AnalysisRuns");
                });

            modelBuilder.Entity("BackPredictFinance.Datas.Entities.Analytic", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Referer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Request")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Analytics");
                });

            modelBuilder.Entity("BackPredictFinance.Datas.Entities.Asset", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AssetType")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Country")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime?>("LastProfileSyncUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderSymbol")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Sector")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Summary")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("BackPredictFinance.Datas.Entities.AssetCandleSnapshot", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Close")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("High")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<string>("Interval")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<decimal>("Low")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("Open")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Volume")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId", "Interval", "TimestampUtc")
                        .IsUnique();

                    b.ToTable("AssetCandleSnapshots");
                });

            modelBuilder.Entity("BackPredictFinance.Datas.Entities.AssetPeaEligibility", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CheckedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("EligibilityStatus")
                        .HasColumnType("int");

                    b.Property<string>("PolicyVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ReviewerNote")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("SourceReference")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("SourceType")
                        .HasColumnType("int");

                    b.Property<string>("UniverseId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssetId", "UniverseId")
                        .IsUnique();

                    b.HasIndex("UniverseId", "EligibilityStatus");

                    b.ToTable("AssetPeaEligibilities");
                });

            modelBuilder.Entity("BackPredictFinance.Datas.Entities.AssetQuoteSnapshot", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("AsOfUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DayVariationPct")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal>("LastPrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssetId", "AsOfUtc");

                    b.ToTable("AssetQuoteSnapshots");
                });

            modelBuilder.Entity("BackPredictFinance.Datas.Entities.AssetTransaction", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Fees")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAssetId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserAssetId", "TimestampUtc");

                    b.ToTable("AssetTransactions", t =>
                        {
                            t.HasCheckConstraint("CK_AssetTransactions_Fees_NonNegative", "[Fees] >= 0");

                            t.HasCheckConstraint("CK_AssetTransactions_Quantity_Positive", "[Quantity] > 0");

                            t.HasCheckConstraint("CK_AssetTransactions_UnitPrice_Positive", "[UnitPrice] > 0");
                        });
                });

            modelBuilder.Entity("BackPredictFinance.Datas.Entities.DecisionSignal", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<string>("AnalysisRunId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("HorizonDays")
                        .HasColumnType("int");

                    b.Property<bool>("IsActionable")
                        .HasColumnType("bit");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisRunId")
                        .IsUnique();

                    b.ToTable("DecisionSignals");
                });

            modelBuilder.Entity("BackPredictFinance.Datas.Entities.ModelSnapshot", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AnalysisRunId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("F1")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("ModelMessage")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("ModelStatus")
                        .HasColumnType("int");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("PositiveSamples")
                        .HasColumnType("int");

                    b.Property<decimal?>("Precision")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("RocAuc")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("SelectedThreshold")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisRunId")
                        .IsUnique();

                    b.ToTable("ModelSnapshots");
                });

            modelBuilder.Entity("BackPredictFinance.Datas.Entities.ParameterDictionaryEntry", b =>
                {
                    b.Property<string>("ParameterId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayLabel")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("HowToRead")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("ImplicationWithPosition")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("ImplicationWithoutPosition")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("LimitsOfInterpretation")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("RoleInCategory")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("SimpleDefinition")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("WhatItDoesNotProve")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("WhatItSupports")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("WhyItMatters")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.HasKey("ParameterId");

                    b.HasIndex("CategoryCode", "IsPublished", "IsActive");

                    b.ToTable("ParameterDictionaryEntries");

                    b.HasData(
                        new
                        {
                            ParameterId = "returnOnEquity",
                            CategoryCode = "profitability",
                            CreatedAtUtc = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayLabel = "Return on equity",
                            HowToRead = "A higher value generally indicates stronger capital efficiency, as long as it is not inflated by an unusually low equity base.",
                            ImplicationWithPosition = "With a position, it can reinforce conviction in the business profile, but it does not replace risk management or invalidation levels.",
                            ImplicationWithoutPosition = "Without a position, use it to qualify business quality, not to replace market-timing analysis.",
                            IsActive = true,
                            IsPublished = true,
                            LimitsOfInterpretation = "Read it with debt and margin metrics because a high value alone can hide balance-sheet fragility.",
                            RoleInCategory = "Measure how efficiently the company turns shareholder capital into profit.",
                            SimpleDefinition = "Return on equity compares net profit to shareholder equity.",
                            WhatItDoesNotProve = "It does not prove that the stock is cheap, timely to buy, or protected from a reversal on its own.",
                            WhatItSupports = "It supports a profitability reading when it stays coherent with the rest of the operating picture.",
                            WhyItMatters = "It helps beginners see whether profitability is supported by the capital already invested in the business."
                        },
                        new
                        {
                            ParameterId = "operatingMargin",
                            CategoryCode = "profitability",
                            CreatedAtUtc = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayLabel = "Operating margin",
                            HowToRead = "A higher value generally means the core activity keeps more room after operating expenses.",
                            ImplicationWithPosition = "With a position, it can help explain why the company may remain robust, but it does not erase timing or trend risk.",
                            ImplicationWithoutPosition = "Without a position, it can help you understand business resilience before going further.",
                            IsActive = true,
                            IsPublished = true,
                            LimitsOfInterpretation = "It can vary by sector and cycle, so it must be read against the company context and not with a universal threshold.",
                            RoleInCategory = "Show how much operating profit remains after core operating costs.",
                            SimpleDefinition = "Operating margin compares operating income to revenue.",
                            WhatItDoesNotProve = "It does not prove future growth, balance-sheet safety, or a final recommendation on its own.",
                            WhatItSupports = "It supports the reading that the business may have pricing power or cost discipline.",
                            WhyItMatters = "It helps judge whether profitability comes from the normal business activity rather than from exceptional items."
                        },
                        new
                        {
                            ParameterId = "currentRatio",
                            CategoryCode = "liquidity",
                            CreatedAtUtc = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayLabel = "Current ratio",
                            HowToRead = "A higher value generally suggests more short-term balance-sheet flexibility, but an extreme value can also reflect idle assets.",
                            ImplicationWithPosition = "With a position, it can reduce some short-term stress concerns, but it does not replace portfolio discipline.",
                            ImplicationWithoutPosition = "Without a position, use it as a balance-sheet comfort signal, not as a trigger.",
                            IsActive = true,
                            IsPublished = true,
                            LimitsOfInterpretation = "It says little about long-term competitiveness and can differ strongly by industry.",
                            RoleInCategory = "Indicate how short-term assets compare to short-term liabilities.",
                            SimpleDefinition = "Current ratio compares current assets to current liabilities.",
                            WhatItDoesNotProve = "It does not prove profitability, attractive valuation, or a good entry point on its own.",
                            WhatItSupports = "It supports a liquidity reading when short-term flexibility matters in the business context.",
                            WhyItMatters = "It helps beginners understand whether the company appears able to absorb near-term obligations."
                        },
                        new
                        {
                            ParameterId = "debtToEquity",
                            CategoryCode = "debt",
                            CreatedAtUtc = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayLabel = "Debt to equity",
                            HowToRead = "A lower value generally indicates a lighter leverage profile, though normal levels differ by sector.",
                            ImplicationWithPosition = "With a position, it can frame how much leverage risk you are carrying, but it does not dictate the action by itself.",
                            ImplicationWithoutPosition = "Without a position, it can help filter out balance-sheet profiles that do not match your caution level.",
                            IsActive = true,
                            IsPublished = true,
                            LimitsOfInterpretation = "A single ratio cannot describe debt quality, refinancing profile, or cash generation by itself.",
                            RoleInCategory = "Show how much debt stands against shareholder equity.",
                            SimpleDefinition = "Debt to equity compares the debt burden to the equity base.",
                            WhatItDoesNotProve = "It does not prove that the company is safe in all scenarios or that the share is attractive now.",
                            WhatItSupports = "It supports a leverage-risk reading when combined with profitability and liquidity data.",
                            WhyItMatters = "It helps evaluate whether the company could become fragile if conditions deteriorate."
                        },
                        new
                        {
                            ParameterId = "trailingPe",
                            CategoryCode = "valuation",
                            CreatedAtUtc = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayLabel = "Trailing P/E",
                            HowToRead = "A lower value can indicate a cheaper valuation, but only relative to the company quality, growth profile, and sector norms.",
                            ImplicationWithPosition = "With a position, it can help you reassess valuation stretch, but it does not replace the technical and portfolio context.",
                            ImplicationWithoutPosition = "Without a position, it can help you judge whether the market price already embeds optimism.",
                            IsActive = true,
                            IsPublished = true,
                            LimitsOfInterpretation = "It becomes weak when earnings are cyclical, temporarily distorted, or negative.",
                            RoleInCategory = "Compare the share price to trailing earnings per share.",
                            SimpleDefinition = "Trailing P/E expresses how many times the market values the last reported earnings.",
                            WhatItDoesNotProve = "It does not prove that the stock is undervalued, safe, or ready to buy on its own.",
                            WhatItSupports = "It supports a valuation reading when earnings remain meaningful and comparable.",
                            WhyItMatters = "It helps beginners see that a stock price should be read against earnings, not in isolation."
                        },
                        new
                        {
                            ParameterId = "dividendYield",
                            CategoryCode = "dividend",
                            CreatedAtUtc = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayLabel = "Dividend yield",
                            HowToRead = "A higher value can mean stronger income potential, but it can also reflect a falling share price or an unsustainable payout.",
                            ImplicationWithPosition = "With a position, it can explain part of the holding case, but it does not replace monitoring of trend, risk, and fundamentals.",
                            ImplicationWithoutPosition = "Without a position, it can clarify whether the stock fits an income objective, but not whether the timing is right.",
                            IsActive = true,
                            IsPublished = true,
                            LimitsOfInterpretation = "It must be read with payout sustainability and business quality, not as a standalone quality label.",
                            RoleInCategory = "Relate the dividend distribution to the current share price.",
                            SimpleDefinition = "Dividend yield compares the annual dividend to the current market price.",
                            WhatItDoesNotProve = "It does not prove valuation attractiveness, price support, or future dividend safety on its own.",
                            WhatItSupports = "It supports an income-oriented reading when the payout looks sustainable.",
                            WhyItMatters = "It helps beginners distinguish income characteristics from pure price expectations."
                        });
                });

            modelBuilder.Entity("BackPredictFinance.Datas.Entities.PatternAssessment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AnalysisRunId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CurrentPrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<DateTime?>("FirstPeakAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("InvalidationPrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<decimal?>("NecklinePrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<string>("PatternId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<decimal>("Probability")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<DateTime?>("SecondPeakAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("TargetPrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisRunId", "IsPrimary");

                    b.ToTable("PatternAssessments");
                });

            modelBuilder.Entity("BackPredictFinance.Datas.Entities.PriceHistory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<DateTime>("RetrievedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Volume")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId", "RetrievedAtUtc");

                    b.ToTable("PriceHistories", t =>
                        {
                            t.HasCheckConstraint("CK_PriceHistories_Price_Positive", "[Price] > 0");
                        });
                });

            modelBuilder.Entity("BackPredictFinance.Datas.Entities.Recommendation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("decimal(5,4)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RecommendedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("TargetPrice")
                        .HasColumnType("decimal(18,8)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAssetId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserAssetId");

                    b.ToTable("Recommendations");
                });

            modelBuilder.Entity("BackPredictFinance.Datas.Entities.RecommendationWordingScenario", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ActionVerbFamilyCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("HoldingStatus")
                        .HasColumnType("int");

                    b.Property<int>("RecommendationKind")
                        .HasColumnType("int");

                    b.Property<string>("RecommendationStrengthFamily")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ScenarioCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TemplateSummary")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("WordingVersionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("RecommendationKind", "HoldingStatus");

                    b.HasIndex("WordingVersionId", "ScenarioCode")
                        .IsUnique();

                    b.ToTable("RecommendationWordingScenarios");

                    b.HasData(
                        new
                        {
                            Id = "SCN_NOT_HELD_BUY",
                            ActionVerbFamilyCode = "BUY",
                            CreatedAtUtc = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            HoldingStatus = 0,
                            RecommendationKind = 1,
                            RecommendationStrengthFamily = "Low,Medium,High",
                            ScenarioCode = "NOT_HELD_BUY",
                            TemplateSummary = "Acheter avec suffixe de force fort, moyen, ou faible pour une lecture d'entree pedagogique.",
                            WordingVersionId = "REC_WORDING_V1"
                        },
                        new
                        {
                            Id = "SCN_NOT_HELD_MONITOR",
                            ActionVerbFamilyCode = "MONITOR",
                            CreatedAtUtc = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            HoldingStatus = 0,
                            RecommendationKind = 0,
                            RecommendationStrengthFamily = "Low,Medium,High",
                            ScenarioCode = "NOT_HELD_MONITOR",
                            TemplateSummary = "Surveiller avec suffixe de force fort, moyen, ou faible tant que le signal n'est pas confirme.",
                            WordingVersionId = "REC_WORDING_V1"
                        },
                        new
                        {
                            Id = "SCN_NOT_HELD_WAIT",
                            ActionVerbFamilyCode = "WAIT",
                            CreatedAtUtc = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            HoldingStatus = 0,
                            RecommendationKind = 2,
                            RecommendationStrengthFamily = "Low,Medium,High",
                            ScenarioCode = "NOT_HELD_WAIT",
                            TemplateSummary = "Attendre avec une formulation prudente qui refuse une prise de position immediate.",
                            WordingVersionId = "REC_WORDING_V1"
                        },
                        new
                        {
                            Id = "SCN_HELD_HOLD",
                            ActionVerbFamilyCode = "HOLD",
                            CreatedAtUtc = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            HoldingStatus = 1,
                            RecommendationKind = 3,
                            RecommendationStrengthFamily = "Low,Medium,High",
                            ScenarioCode = "HELD_HOLD",
                            TemplateSummary = "Conserver avec suffixe de force fort, moyen, ou faible pour une position deja detenue.",
                            WordingVersionId = "REC_WORDING_V1"
                        },
                        new
                        {
                            Id = "SCN_HELD_REINFORCE",
                            ActionVerbFamilyCode = "REINFORCE",
                            CreatedAtUtc = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            HoldingStatus = 1,
                            RecommendationKind = 4,
                            RecommendationStrengthFamily = "Low,Medium,High",
                            ScenarioCode = "HELD_REINFORCE",
                            TemplateSummary = "Renforcer avec suffixe de force fort, moyen, ou faible pour une position deja detenue.",
                            WordingVersionId = "REC_WORDING_V1"
                        },
                        new
                        {
                            Id = "SCN_HELD_SELL",
                            ActionVerbFamilyCode = "SELL",
                            CreatedAtUtc = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            HoldingStatus = 1,
                            RecommendationKind = 6,
                            RecommendationStrengthFamily = "Low,Medium,High",
                            ScenarioCode = "HELD_SELL",
                            TemplateSummary = "Vendre avec suffixe de force fort, moyen, ou faible pour une sortie pedagogique de position.",
                            WordingVersionId = "REC_WORDING_V1"
                        },
                        new
                        {
                            Id = "SCN_HELD_WAIT",
                            ActionVerbFamilyCode = "WAIT",
                            CreatedAtUtc = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            HoldingStatus = 1,
                            RecommendationKind = 2,
                            RecommendationStrengthFamily = "Low,Medium,High",
                            ScenarioCode = "HELD_WAIT",
                            TemplateSummary = "Attendre avec une formulation prudente qui ne force pas de changement de posture sur la position actuelle.",
                            WordingVersionId = "REC_WORDING_V1"
                        });
                });

            modelBuilder.Entity("BackPredictFinance.Datas.Entities.RecommendationWordingVersion", b =>
                {
                    b.Property<string>("WordingVersionId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("ActivatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("AffectedDomains")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("ExplanationPolicyVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RecommendationPolicyVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("WordingVersionId");

                    b.HasIndex("IsActive", "ActivatedAtUtc");

                    b.ToTable("RecommendationWordingVersions");

                    b.HasData(
                        new
                        {
                            WordingVersionId = "REC_WORDING_V1",
                            ActivatedAtUtc = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            AffectedDomains = "recommendation,explanation",
                            CreatedAtUtc = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "PredictFinance V1 recommendation wording",
                            ExplanationPolicyVersion = "analysis-v1-explanation@prompt5",
                            IsActive = true,
                            RecommendationPolicyVersion = "analysis-v1-policy@prompt3"
                        });
                });

            modelBuilder.Entity("BackPredictFinance.Datas.Entities.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FingerprintHash")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("BackPredictFinance.Datas.Entities.SignalOutcome", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AnalysisRunId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ConfidenceLabel")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DecisionSignalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("EvaluatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("EvaluationWindowDays")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FirstHitAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Outcome")
                        .HasColumnType("int");

                    b.Property<string>("PatternAssessmentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PolicyVersion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisRunId");

                    b.HasIndex("DecisionSignalId");

                    b.HasIndex("EvaluatedAtUtc");

                    b.HasIndex("PatternAssessmentId")
                        .IsUnique();

                    b.ToTable("SignalOutcomes");
                });

            modelBuilder.Entity("BackPredictFinance.Datas.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("AnalyticsConsent")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ConsentLastUpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastConnection")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("MarketingEmailConsent")
                        .HasColumnType("bit");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("ProductImprovementConsent")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("BackPredictFinance.Datas.Entities.UserAsset", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("UserId", "AssetId")
                        .IsUnique();

                    b.ToTable("UserAssets", t =>
                        {
                            t.HasCheckConstraint("CK_UserAssets_Quantity_NonNegative", "[Quantity] >= 0");
                        });
                });

            modelBuilder.Entity("BackPredictFinance.Datas.Entities.UserNotification", b =>
                {
                    b.Property<string>("NotificationId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReadAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("TargetEntityId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("TargetScreen")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId", "Category", "CreatedAtUtc");

                    b.HasIndex("UserId", "Status", "CreatedAtUtc");

                    b.ToTable("UserNotifications");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BackPredictFinance.Datas.Entities.AnalysisRun", b =>
                {
                    b.HasOne("BackPredictFinance.Datas.Entities.Asset", "Asset")
                        .WithMany("AnalysisRuns")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackPredictFinance.Datas.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackPredictFinance.Datas.Entities.AssetCandleSnapshot", b =>
                {
                    b.HasOne("BackPredictFinance.Datas.Entities.Asset", "Asset")
                        .WithMany("CandleSnapshots")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("BackPredictFinance.Datas.Entities.AssetPeaEligibility", b =>
                {
                    b.HasOne("BackPredictFinance.Datas.Entities.Asset", "Asset")
                        .WithMany("PeaEligibilities")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("BackPredictFinance.Datas.Entities.AssetQuoteSnapshot", b =>
                {
                    b.HasOne("BackPredictFinance.Datas.Entities.Asset", "Asset")
                        .WithMany("QuoteSnapshots")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("BackPredictFinance.Datas.Entities.AssetTransaction", b =>
                {
                    b.HasOne("BackPredictFinance.Datas.Entities.UserAsset", "UserAsset")
                        .WithMany()
                        .HasForeignKey("UserAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAsset");
                });

            modelBuilder.Entity("BackPredictFinance.Datas.Entities.DecisionSignal", b =>
                {
                    b.HasOne("BackPredictFinance.Datas.Entities.AnalysisRun", "AnalysisRun")
                        .WithOne("DecisionSignal")
                        .HasForeignKey("BackPredictFinance.Datas.Entities.DecisionSignal", "AnalysisRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisRun");
                });

            modelBuilder.Entity("BackPredictFinance.Datas.Entities.ModelSnapshot", b =>
                {
                    b.HasOne("BackPredictFinance.Datas.Entities.AnalysisRun", "AnalysisRun")
                        .WithOne("ModelSnapshot")
                        .HasForeignKey("BackPredictFinance.Datas.Entities.ModelSnapshot", "AnalysisRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisRun");
                });

            modelBuilder.Entity("BackPredictFinance.Datas.Entities.PatternAssessment", b =>
                {
                    b.HasOne("BackPredictFinance.Datas.Entities.AnalysisRun", "AnalysisRun")
                        .WithMany("PatternAssessments")
                        .HasForeignKey("AnalysisRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisRun");
                });

            modelBuilder.Entity("BackPredictFinance.Datas.Entities.PriceHistory", b =>
                {
                    b.HasOne("BackPredictFinance.Datas.Entities.Asset", "Asset")
                        .WithMany("PriceHistories")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("BackPredictFinance.Datas.Entities.Recommendation", b =>
                {
                    b.HasOne("BackPredictFinance.Datas.Entities.UserAsset", "UserAsset")
                        .WithMany("Recommendations")
                        .HasForeignKey("UserAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAsset");
                });

            modelBuilder.Entity("BackPredictFinance.Datas.Entities.RecommendationWordingScenario", b =>
                {
                    b.HasOne("BackPredictFinance.Datas.Entities.RecommendationWordingVersion", "WordingVersion")
                        .WithMany("Scenarios")
                        .HasForeignKey("WordingVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WordingVersion");
                });

            modelBuilder.Entity("BackPredictFinance.Datas.Entities.RefreshToken", b =>
                {
                    b.HasOne("BackPredictFinance.Datas.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackPredictFinance.Datas.Entities.SignalOutcome", b =>
                {
                    b.HasOne("BackPredictFinance.Datas.Entities.AnalysisRun", "AnalysisRun")
                        .WithMany()
                        .HasForeignKey("AnalysisRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackPredictFinance.Datas.Entities.DecisionSignal", "DecisionSignal")
                        .WithMany()
                        .HasForeignKey("DecisionSignalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackPredictFinance.Datas.Entities.PatternAssessment", "PatternAssessment")
                        .WithMany()
                        .HasForeignKey("PatternAssessmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AnalysisRun");

                    b.Navigation("DecisionSignal");

                    b.Navigation("PatternAssessment");
                });

            modelBuilder.Entity("BackPredictFinance.Datas.Entities.UserAsset", b =>
                {
                    b.HasOne("BackPredictFinance.Datas.Entities.Asset", "Asset")
                        .WithMany("UserAssets")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackPredictFinance.Datas.Entities.User", "User")
                        .WithMany("UserAssets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackPredictFinance.Datas.Entities.UserNotification", b =>
                {
                    b.HasOne("BackPredictFinance.Datas.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BackPredictFinance.Datas.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BackPredictFinance.Datas.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackPredictFinance.Datas.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BackPredictFinance.Datas.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackPredictFinance.Datas.Entities.AnalysisRun", b =>
                {
                    b.Navigation("DecisionSignal");

                    b.Navigation("ModelSnapshot");

                    b.Navigation("PatternAssessments");
                });

            modelBuilder.Entity("BackPredictFinance.Datas.Entities.Asset", b =>
                {
                    b.Navigation("AnalysisRuns");

                    b.Navigation("CandleSnapshots");

                    b.Navigation("PeaEligibilities");

                    b.Navigation("PriceHistories");

                    b.Navigation("QuoteSnapshots");

                    b.Navigation("UserAssets");
                });

            modelBuilder.Entity("BackPredictFinance.Datas.Entities.RecommendationWordingVersion", b =>
                {
                    b.Navigation("Scenarios");
                });

            modelBuilder.Entity("BackPredictFinance.Datas.Entities.User", b =>
                {
                    b.Navigation("UserAssets");
                });

            modelBuilder.Entity("BackPredictFinance.Datas.Entities.UserAsset", b =>
                {
                    b.Navigation("Recommendations");
                });
#pragma warning restore 612, 618
        }
    }
}
